---
all:
  hosts:
    host-lt:
      ansible_host: 51.250.18.171
    host-vc:
      ansible_host: 51.250.97.219
    host-cl:
      ansible_host: 51.250.100.77
  vars:
    ansible_connection: ssh
    ansible_user: arsen
    ansible_python_interpreter: /usr/bin/python3
clickhouse:
  hosts:
    host-cl:
# vector:
#   hosts:
#     host-vc:
lighthouse:
  hosts:
    host-lt: